Repository CA-G12/Holidays, pull requests merged in 2022-08, with the labels that each got.

#2 create file structure
  .env
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  public/errors/400.html
  public/errors/500.html
  public/errors/errorsStyle.css
  public/index.html
  public/js/dom.js
  public/js/index.js
  public/style.css
  src/app.js
  src/controllers/index.js
  src/routers/index.js
  tests/test.js
Labels: Approved

#7 Handle errors
  package-lock.json
  package.json
  public/errors/400.html
  public/errors/500.html
  src/app.js
  src/controllers/errors.js
Labels: Approved

#10 adding header and table for viewing table
  public/img/background.png
  public/img/holidays.png
  public/index.html
  public/js/dom.js
  public/style.css
Labels: Approved

#13 handle countries values and put them in the drop down menu, put curre…
  public/index.html
  public/js/dom.js
  public/style.css
Labels: Approved

#15 display country name instead of country code
  public/js/dom.js
  src/app.js
Labels: Waiting Review

#19 add readme file
  README.md
Labels: Done
